// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/colaboradores": {
            "post": {
                "description": "Cria um novo colaborador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "colaboradores"
                ],
                "summary": "Criar colaborador",
                "parameters": [
                    {
                        "description": "Dados do colaborador",
                        "name": "colaborador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Colaborador"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Colaborador"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/colaboradores/listar": {
            "post": {
                "description": "Lista colaboradores com filtros e paginação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "colaboradores"
                ],
                "summary": "Listar colaboradores",
                "parameters": [
                    {
                        "description": "Filtros e paginação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ColaboradorListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/colaboradores/{id}": {
            "get": {
                "description": "Retorna um colaborador e o nome do gerente",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "colaboradores"
                ],
                "summary": "Buscar colaborador por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do colaborador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ColaboradorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza os dados de um colaborador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "colaboradores"
                ],
                "summary": "Atualizar colaborador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do colaborador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do colaborador",
                        "name": "colaborador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Colaborador"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Colaborador"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um colaborador",
                "tags": [
                    "colaboradores"
                ],
                "summary": "Deletar colaborador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do colaborador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/departamentos": {
            "post": {
                "description": "Cria um novo departamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departamentos"
                ],
                "summary": "Criar departamento",
                "parameters": [
                    {
                        "description": "Dados do departamento",
                        "name": "departamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Departamento"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Departamento"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/departamentos/listar": {
            "post": {
                "description": "Lista departamentos com filtros e paginação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departamentos"
                ],
                "summary": "Listar departamentos",
                "parameters": [
                    {
                        "description": "Filtros e paginação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DepartamentoListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/departamentos/{id}": {
            "get": {
                "description": "Retorna um departamento com sua árvore hierárquica",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departamentos"
                ],
                "summary": "Buscar departamento por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do departamento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DepartamentoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza os dados de um departamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departamentos"
                ],
                "summary": "Atualizar departamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do departamento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do departamento",
                        "name": "departamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Departamento"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Departamento"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um departamento",
                "tags": [
                    "departamentos"
                ],
                "summary": "Deletar departamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do departamento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/gerentes/{id}/colaboradores": {
            "get": {
                "description": "Retorna todos os colaboradores dos departamentos subordinados ao gerente",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gerentes"
                ],
                "summary": "Listar colaboradores subordinados ao gerente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do gerente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Colaborador"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Colaborador": {
            "type": "object",
            "required": [
                "cpf",
                "departamento_id",
                "nome"
            ],
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "departamento": {
                    "$ref": "#/definitions/domain.Departamento"
                },
                "departamento_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "rg": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ColaboradorListRequest": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "departamento_id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "rg": {
                    "type": "string"
                }
            }
        },
        "domain.ColaboradorResponse": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "departamento_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "nome_gerente": {
                    "type": "string"
                },
                "rg": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Departamento": {
            "type": "object",
            "required": [
                "gerente_id",
                "nome"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "departamento_superior": {
                    "$ref": "#/definitions/domain.Departamento"
                },
                "departamento_superior_id": {
                    "type": "string"
                },
                "gerente": {
                    "$ref": "#/definitions/domain.Colaborador"
                },
                "gerente_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "subdepartamentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Departamento"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.DepartamentoListRequest": {
            "type": "object",
            "properties": {
                "departamento_superior_id": {
                    "type": "string"
                },
                "gerente_nome": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "domain.DepartamentoResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "departamento_superior_id": {
                    "type": "string"
                },
                "gerente_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "nome_gerente": {
                    "type": "string"
                },
                "subdepartamentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DepartamentoResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Colaboradores e Departamentos",
	Description:      "API REST para gerenciar colaboradores e departamentos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
